name: Issue generator

on:
  milestone:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: ./tools/recurrent-issues-generator/CreateRecurrentIssues.ps1
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.WRONG_TOKEN }}