name: Issue generator

on:
  milestone:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a multi-line script
      run: ./test.ps1
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}